# Generated by Django 2.0.1 on 2018-02-01 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180201_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
