# Generated by Django 2.0.1 on 2018-02-01 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180202_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
