# Generated by Django 2.0.1 on 2018-02-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180202_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylog',
            old_name='users',
            new_name='customers',
        ),
        migrations.RenameField(
            model_name='companylog',
            old_name='activity_week',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='companylog',
            name='cohort_week',
        ),
    ]
