# Generated by Django 2.0.1 on 2018-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180203_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='file_url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='companylog',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
