# Generated by Django 2.0.1 on 2018-02-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_company_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='file_url',
        ),
    ]
