# Generated by Django 2.0.1 on 2018-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_company_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylog',
            name='day',
            field=models.IntegerField(default=0, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='companylog',
            name='month',
            field=models.IntegerField(default=0, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='companylog',
            name='year',
            field=models.IntegerField(default=0, verbose_name='year'),
        ),
    ]
